update pipelines first attempt

diff --git a/pipelines/templates/build-test-publish.yaml b/pipelines/templates/build-test-publish.yaml
--- a/pipelines/templates/build-test-publish.yaml
+++ b/pipelines/templates/build-test-publish.yaml
@@ -183,12 +183,9 @@ stages:
               script: |
                 set -eux  # fail on error
 
-                # Only dep v 0.5.0 works.
-                # download specific version
-                DEP_VERSION="0.5.0"
-                curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
-                chmod +x $GOPATH/bin/dep
-                dep ensure
+                # download golangci-lint
+                curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(GOBIN) v1.27.0
+                go mod download -x
 
                 # install dependency libraries
                 sudo apt-get update
@@ -245,12 +242,9 @@ stages:
               script: |
                 set -eux  # fail on error
 
-                # Only dep v 0.5.0 works.
-                # download specific version
-                DEP_VERSION="0.5.0"
-                curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
-                chmod +x $GOPATH/bin/dep
-                dep ensure
+                # download golangci-lint
+                curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(GOBIN) v1.27.0
+                go mod download -x
 
           # Do not change the implementation of this stage without changing the steps in docs/development.md
           - task: Bash@3
@@ -290,6 +284,74 @@ stages:
   # and publishes artifacts to target and with labels that depend on the
   # built branch.
   - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
+
+    # Env
+    - stage: Setup
+      displayName: Set Pipeline globals
+      dependsOn: []
+      pool:
+        vmImage: 'ubuntu-latest'
+      jobs:
+
+      - job: SetBuildDep
+        displayName: Set base container build
+        steps:
+          # - template: ./free-agent-disk.yaml
+          - task: Bash@3
+            displayName: 'Git diff verify deps build'
+            inputs:
+              targetType: 'inline'
+              script: |
+                set -eux  # fail on error
+
+                MASTER="remotes/origin/master"
+                GIT_DIFF_SOURCEBRANCH="HEAD"
+                # Set build_deps Triggers to false
+                BUILD_DEPS=false
+                DEPS_LABEL=latest
+
+                # we should always use master as a comparison, except in the case that this is
+                # a build for master. In this case we can use HEAD~ (1 commit behind master)
+                # because all merges will be squash merges
+                if [[ $(git diff "$MASTER") ]]; then
+                    GIT_DIFF_UPSTREAMBRANCH="$MASTER"
+                else
+                    GIT_DIFF_UPSTREAMBRANCH="$MASTER~"
+                fi
+                echo "GIT_DIFF_UPSTREAMBRANCH: $GIT_DIFF_UPSTREAMBRANCH"
+                echo "GIT_DIFF_SOURCEBRANCH: $GIT_DIFF_SOURCEBRANCH"
+                FILE_CHANGE_SET=$(git diff "$GIT_DIFF_SOURCEBRANCH" "$GIT_DIFF_UPSTREAMBRANCH" --name-only)
+                echo "Files changed since last commit..."
+                echo "$FILE_CHANGE_SET"
+
+                # if git diff detects commits made to the deps files we build the dep containerss
+                if [[ ! -z "$(echo $FILE_CHANGE_SET | grep -e 'go.mod' -e 'Dockerfile.python.deps' -e 'Dockerfile.golang.deps' -e 'Dockerfile.python.deps' -e 'presidio-analyzer/Pipfile' -e 'presidio-analyzer/Pipfile.lock')" ]]; then
+                    echo "Performing build deps."
+                    BUILD_DEPS=true
+                    DEPS_LABEL=$(Build.BuildId)
+                fi
+
+                echo "##vso[task.setvariable variable=BUILD_DEPS]$BUILD_DEPS"
+                echo "##vso[task.setvariable variable=DEPS_LABEL]$DEPS_LABEL"
+          # To pass the variable build_deps, we write it to a file
+          - task: Bash@3
+            displayName: Copy Artifacts
+            name: setEnv
+            inputs:
+              targetType: 'inline'
+              script: |
+                set -eux  # fail on error
+
+                mkdir -p $(Pipeline.Workspace)/variables
+                echo "$DEPS_LABEL" > $(Pipeline.Workspace)/variables/DEPS_LABEL
+                echo "$BUILD_DEPS" > $(Pipeline.Workspace)/variables/BUILD_DEPS
+                echo "##vso[task.setvariable variable=BUILD_DEPS;isOutput=true]$BUILD_DEPS"
+                echo "##vso[task.setvariable variable=DEPS_LABEL;isOutput=true]$DEPS_LABEL"
+          # Publish the folder as pipeline artifact
+          - publish: $(Pipeline.Workspace)/variables
+            displayName: Publish Artifacts
+            artifact: variables
+
     # Python Stage
     - stage: PythonStage
       displayName: Build Python
